name: Selenium TestNG CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Chrome & ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable unzip
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
        echo "Chrome major version: $CHROME_VERSION"
        wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION
        VERSION=$(cat LATEST_RELEASE_$CHROME_VERSION)
        echo "ChromeDriver version to install: $VERSION"
        wget https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Cache Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('**/pom.xml') }}

    - name: Run tests with Maven
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        mvn clean test

    - name: Upload Extent Report
      uses: actions/upload-artifact@v4
      with:
        name: ExtentReports
        path: reports/
